### PR TITLE
GetQuestID replacement for pre-4.0 clients

### PR DESCRIPTION
**Pull request by xvwyh**

### CODE REVIEW

**Comment by Koward** [comment]
Couldn't that be its own addon/lib? Other addons might benefit, and it's well scoped.

**Comment by xvwyh** [comment]
It could be, but I'm not sure how failproof it is. Currently its data is limited to quests that have VO, I haven't tried checking what's the situation if I include all Vanilla quests and also TBC and WotLK quests. Don't know what the database size will be either.

But the biggest issue is that it relies on DB data to be the same between the DB used for this addon (vmangos) and the DB used on the server you're currently playing on. If a quest is offered/rewarded by a different NPC - the lookup might fail. If quests texts differ in some way - the lookup will fail. I tried to minimize the latter by excluding everything except for latin characters from the hash. This is less of an issue when used within just this addon: if there's a mismatch in the quest text or the npc - it's ok to fail the ID lookup, because that probably means that the VO would be wrong too (wrong race/gender of the speaker, wrong words). But it this was a general library - such behavior won't fly.

And then there's the issue of other locales. Again, in this addon this doesn't matter, because the VO is english-only, so we only need to care about players on the english client. But each other locale would require its own hash lookup database. But that's the lesser evil still. The greater evil is UTF-8. Lua patterns work with latin text just fine, but double-byte+ characters in UTF-8 would break it completely, as Lua is going to treat each byte as a separate character. Any sort of work with non-english text in Lua has to be done through external UTF-8 libraries, and I doubt there's one that reimplements patterns (or even regexps) to make them UTF-8 compatible.

**Comment by mrthinger** [comment]
im working on a 1.12 replacement

**Comment by xvwyh** [comment]
I'm going with MrThinger's implementation so that we can share the code and data between 1.12 and 3.3.5. My solution stays up in my repo for historical reasons, might help someone someday.

**Pull request closed without merging**
